# render.yaml
services:
  - type: web
    name: citizens-or-crooks
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        value: "postgresql://citizens_user:GuqgrLd0GPzUnGNBynm6igYdB70VgBsv@dpg-cv8jgdrqf0us73b95h10-a.oregon-postgres.render.com/citizens_db"
    autoDeploy: true
databases:
  - name: citizens_db
    databaseName: citizens_db
    user: citizens_user
    plan: free
    ipAllowList: []