services:
  - type: web
    name: citizens-or-crooks
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_ENV
        value: production
databases:
  - name: citizens_db
    databaseName: citizens_db
    user: citizens_user
    plan: free